- name: installing packages
  hosts: node1
  tasks: #list of tasks
  - name: installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed
  
  - name: start service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes