- name: conditions
  hosts: localhost
  tasks: #list of tasks
  - name: check user exists or not
    ansible.builtin.command: id expense
    ignore_errors: yes
    register: user_info

  - name: print user details
    ansible.builtin.debug:
      msg: "user info : {{user_info}}"
  
  - name: creating user
    ansible.builtin.command: useradd expense
    when: user_info.rc !=0

  - name: end of ansible
    ansible.builtin.debug:
      msg: "reached end of ansible code"