- name: default value
  hosts: localhost
  tasks: #list of tasks
  - name: print value
    ansible.builtin.debug:
      msg : "Hi, I am {{ name | default('Avinash') }}"

- name: uppercase
  hosts: localhost
  vars:
    greetings: "Hello Good Evening"
  tasks: 
  - name: print uppercase
    ansible.builtin.debug:
      msg: " {{ greetings | upper}} "

- name: lowercase
  hosts: localhost
  vars:
    greetings: "Hello Good Evening"
  tasks: 
  - name: print lowercase
    ansible.builtin.debug:
      msg: " {{ greetings | lower }} "

- name: remove duplicates
  hosts: localhost
  vars:
    num: [1,2,3,4,4,4,5,5,6,6,6,7,7,7]
  tasks: 
  - name: print removing duplicates
    ansible.builtin.debug:
      msg: " {{ num | unique }} "

- name: min and max
  hosts: localhost
  vars:
    ages: [16,26,37,45,59,65,100]
  tasks: 
  - name: print min and max values
    ansible.builtin.debug:
      msg: "min age is: {{ ages | min }} and max age is: {{ ages | max }} "

- name: convert dictionary into lists
  hosts: localhost
  vars:
    my_dict:
      course: Aws
      trainer: Avinash
      duration: 120hrs
  tasks: #list of tasks
  - name: before converting
    ansible.builtin.debug:
      msg: " {{ my_dict }}"

  - name : after converting 
    ansible.builtin.debug:
      msg: " {{ my_dict | dict2items }} "